# Generated by Django 5.1.1 on 2024-10-15 23:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='usuario_FK',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='usuario_FK',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='valoraciones',
        ),
        migrations.AddField(
            model_name='colaborador',
            name='username',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comentario',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comentario',
            name='posts',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='posts.post'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comentario',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='administrado',
            field=models.ManyToManyField(blank=True, to='posts.colaborador'),
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
