# Generated by Django 5.1.1 on 2024-10-16 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_usuario_fk_remove_comentario_usuario_fk_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='administrado',
        ),
    ]
