# Generated by Django 5.1.1 on 2024-10-18 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_remove_post_usuario_fk_post_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagen',
            field=models.ImageField(blank=True, default='/static/post_default.jpg', null=True, upload_to='media'),
        ),
    ]
